export const GET_ALL_ORDERS_USER_REQUEST = "GET_ALL_ORDERS_USER_REQUEST";
export const GET_ALL_ORDERS_USER_SUCCESS = "GET_ALL_ORDERS_USER_SUCCESS";
export const GET_ALL_ORDERS_USER_FAILED = "GET_ALL_ORDERS_USER_FAILED";

export const GET_ALL_ORDERS_SHOP_REQUEST = "GET_ALL_ORDERS_SHOP_REQUEST";
export const GET_ALL_ORDERS_SHOP_SUCCESS = "GET_ALL_ORDERS_SHOP_SUCCESS";
export const GET_ALL_ORDERS_SHOP_FAILED = "GET_ALL_ORDERS_SHOP_FAILED";

export const CLEAR_ORDER_ERRORS = "CLEAR_ORDER_ERRORS";

