// ActionTypesSeller.js
export const LOAD_SELLER_REQUEST = "LOAD_SELLER_REQUEST";
export const LOAD_SELLER_SUCCESS = "LOAD_SELLER_SUCCESS";
export const LOAD_SELLER_FAIL = "LOAD_SELLER_FAIL";
export const GET_ALL_SELLERS_REQUEST = "GET_ALL_SELLERS_REQUEST";
export const GET_ALL_SELLERS_SUCCESS = "GET_ALL_SELLERS_SUCCESS";
export const GET_ALL_SELLERS_FAIL = "GET_ALL_SELLERS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
